### ISSUE TITLE
Broken Apple URL

### ISSUE THREAD

**Issue by ashbaldry** [ashbaldry/appler#3]
The documentation URL for the [iTunes API](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/) is broken.
It has moved to https://performance-partners.apple.com/resources/documentation/itunes-store-web-service-search-api.html

**Comment by PythonCoderUnicorn** [comment]
Hello i know you closed this issue but it is still broken

https://performance-partners.apple.com/resources/documentation/itunes-store-web-service-search-api.html

i get a 404 page

**Comment by ashbaldry** [comment]
Thanks for letting me know @PythonCoderUnicorn 😃  

It looks like the original link now redirects to https://performance-partners.apple.com/search-api, I'll update the DESCRIPTION file. Hopefully they stop moving it!
